# Generated by Django 4.2.6 on 2024-02-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('testname', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
