# Generated by Django 4.2.6 on 2024-03-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tests',
            field=models.ManyToManyField(related_name='records', to='website.test'),
        ),
    ]
