# Generated by Django 4.2.6 on 2024-03-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_record_address_remove_record_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='paid',
            field=models.CharField(default='paid', max_length=50),
        ),
    ]
