# Generated by Django 4.2.6 on 2024-03-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_record_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='lab',
            field=models.CharField(default='own', max_length=50),
        ),
    ]
