# Generated by Django 4.1.13 on 2024-04-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
    ]
